### ISSUE TITLE
Communication issue between Arduino and Tauno serial Plotter

### ISSUE THREAD

**Issue by YoullDuk** [taunoe/tauno-serial-plotter#57]
Hi,
Thank you very much for your work :) 
I have an issue with the serial plotter when I run it using snap or flatpak on my Ubuntu 22.10. 
I am new to Linux interface. 

****Problem :** When I lauch the plotter, no data is plotted and no point appear on the graph.** 

This is the message I get when i lauch the serial plotter from my cmd : 
```
DEBUG:root:Found: 0 lines
DEBUG:root:Init Plot class. With 0 plot lines.
DEBUG:root:0 Open serial: /dev/ttyUSB0 115200
DEBUG:root:1 Open serial: /dev/ttyUSB0 115200
DEBUG:root:ForeverWorker.Run while loop
DEBUG:root:self.plot_exist True
DEBUG:root:self.is_button_connected True
DEBUG:root:before_selected_port /dev/ttyUSB0
INFO:root:read_serial_dat: Incoming data: Initializing SD card...Initialization succedeed.

DEBUG:root:numbers: 0
INFO:root:read_serial_dat: Incoming data: 14,1.41,4.57

DEBUG:root:numbers: 3
INFO:root:read_serial_dat: Incoming data: 14,1.41,4.57

DEBUG:root:numbers: 3
INFO:root:read_serial_dat: Incoming data: 14,1.41,4.57

DEBUG:root:numbers: 3
INFO:root:read_serial_dat: Incoming data: 14,1.41,4.57

DEBUG:root:numbers: 3
INFO:root:read_serial_dat: Incoming data: 14,1.41,4.57

```
Important 
- I am able to plot those same data on Arduino IDE plotter on the same computer using the same USB port
- I installed platformio as mentionned in the requirements
- I carefully followed the connection requirements on usb using : 
```
sudo usermod -a -G dialout $USER
sudo snap connect tauno-serial-plotter:raw-usb
```
How could I fix this issue ? 
Thanks

**Comment by taunoe** [comment]
My first thought: When you are serial printing try using something else instead of a comma (,) maybe dash - or _
Like 14_1.41_4.57

**Comment by YoullDuk** [comment]
Hi, 
Thank you very much with your fast answer. The separator was the issue. "_" works fine on my project :)
Is it possible to set a label for each curve ? 
Thank you for your plotter !
