### ISSUE TITLE
Has it a legend?

### ISSUE THREAD

**Issue by ArminJo** [taunoe/tauno-serial-plotter#58]
The Arduino has a legend where you can assign strings to the colors displayed. Does your program also have this feature? I could not identify it on the screenshots.
Thanks

**Comment by taunoe** [comment]
Good news. Now it displays labels on the graph.
Example Arduino code:
```c++
Serial.print("Label1");
Serial.print(data1);
Serial.print("Label2");
Serial.print(data2);
Serial.println();
```

**Comment by ArminJo** [comment]
Thanks!
I will give it a try.
