### ISSUE TITLE
snap version - no ports show up 

### ISSUE THREAD

**Issue by Richard-Haes-Ellis** [taunoe/tauno-serial-plotter#9]
No ports show on the snap store version, any idea?

**Comment by taunoe** [comment]
Has permission "Access USB hardware directly" enabled?
More information is here: https://snapcraft.io/tauno-serial-plotter

**Comment by taunoe** [comment]
If no ports show up. Then close the app and run these commands. And open the app again:

```Bash
sudo usermod -a -G dialout $USER

sudo snap connect tauno-serial-plotter:raw-usb
```

**Comment by ksaad3747** [comment]
Can't open from CLI or from Applications.
getting this:
------------------------------------------------------------------------------------
Qt: Session management error: Could not open network socket
DEBUG:root:self.selected_baudrate =
DEBUG:root:9600
Fontconfig warning: FcPattern object width does not accept value [75 100)
Segmentation fault (core dumped)
---------------------------------------------------------------------------------------------------

**Comment by taunoe** [comment]
You can try to clean the font cache:

```bash
sudo rm /var/cache/fontconfig/*

rm ~/.cache/fontconfig/*

fc-cache -r
```

**Comment by taunoe** [comment]
If no ports show up. Then close the app and run these commands. And open the app again:
```
sudo usermod -a -G dialout $USER

sudo snap connect tauno-serial-plotter:raw-usb
```
